Cu 865d8neq1
lusis-developers/predix-frontapp pull request #15
Opened 2023-10-18 20:20 UTC by yeyodev1

add terms and conditions page

2023-10-18 20:20 UTC, lualreye commented
Task linked: [CU-865d8neq1 create: terms & conditions page](https://app.clickup.com/t/865d8neq1)

2023-10-27 15:57 UTC, lualreye requested changes

2023-10-27 16:21 UTC, yeyodev1 commented on src/views/TermsAndConditions.vue
I'll be more alert in that cases, sorry

2023-10-27 16:24 UTC, yeyodev1 commented on src/router/index.ts
> +
I thought that there had to be a separation between the ways of import

2023-10-27 16:41 UTC, lualreye approved these changes

2023-10-27 16:41 UTC, merged